# Generated by Django 3.0.3 on 2020-04-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(help_text='Give the book a review', max_length=1000, null=True),
        ),
    ]
