# Generated by Django 3.0.3 on 2020-04-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_bookinstance_imprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='yearPub',
            field=models.DateField(blank=True, null=True),
        ),
    ]
